# Flexoki Dark —— 由 /usr/share/ghostty/themes/Flexoki Dark 生成,勿手改
# 换主题:改 alacritty.toml 里 [general] import 指向的文件名

[colors.primary]
background = "#100f0f"
foreground = "#cecdc3"

[colors.cursor]
text = "#100f0f"
cursor = "#cecdc3"

[colors.vi_mode_cursor]
text = "#100f0f"
cursor = "#4385be"

[colors.selection]
text = "#cecdc3"
background = "#403e3c"

[colors.search.matches]
foreground = "#100f0f"
background = "#878580"

[colors.search.focused_match]
foreground = "#100f0f"
background = "#879a39"

[colors.footer_bar]
foreground = "#cecdc3"
background = "#100f0f"

[colors.hints.start]
foreground = "#100f0f"
background = "#d0a215"

[colors.hints.end]
foreground = "#100f0f"
background = "#878580"

[colors.normal]
black = "#100f0f"
red = "#d14d41"
green = "#879a39"
yellow = "#d0a215"
blue = "#4385be"
magenta = "#ce5d97"
cyan = "#3aa99f"
white = "#878580"

[colors.bright]
black = "#575653"
red = "#af3029"
green = "#66800b"
yellow = "#ad8301"
blue = "#205ea6"
magenta = "#a02f6f"
cyan = "#24837b"
white = "#cecdc3"
