# Kanagawa Dragon —— 由 /usr/share/ghostty/themes/Kanagawa Dragon 生成,勿手改
# 换主题:改 alacritty.toml 里 [general] import 指向的文件名

[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.cursor]
text = "#181616"
cursor = "#c8c093"

[colors.vi_mode_cursor]
text = "#181616"
cursor = "#8ba4b0"

[colors.selection]
text = "#181616"
background = "#c5c9c5"

[colors.search.matches]
foreground = "#181616"
background = "#c8c093"

[colors.search.focused_match]
foreground = "#181616"
background = "#8a9a7b"

[colors.footer_bar]
foreground = "#c5c9c5"
background = "#0d0c0c"

[colors.hints.start]
foreground = "#181616"
background = "#c4b28a"

[colors.hints.end]
foreground = "#181616"
background = "#c8c093"

[colors.normal]
black = "#0d0c0c"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#c8c093"

[colors.bright]
black = "#a6a69c"
red = "#e46876"
green = "#87a987"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#c5c9c5"
