return {
	"pwntester/octo.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-tree/nvim-web-devicons",
	},
	keys = {
		{ "<leader>pr", "<cmd>Octo pr list<cr>", desc = "List GitHub PRs" },
		{ "<leader>po", "<cmd>Octo pr list<cr>", desc = "List and checkout GitHub PR" },
		{ "<leader>pi", "<cmd>Octo issue list<cr>", desc = "List GitHub issues" },
	},
	opts = {
		enable_builtin = true,
		default_to_projects_v2 = true,
		picker = "default",
		pr_auto_merge = false,
		suppress_missing_scope = {
			projects_v2 = true,
		},
		mappings = {
			issue = {
				close_issue = { lhs = "<leader>ic", desc = "close issue" },
				reopen_issue = { lhs = "<leader>io", desc = "reopen issue" },
				list_issues = { lhs = "<leader>il", desc = "list issues" },
				reload = { lhs = "<C-r>", desc = "reload issue" },
				open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
				copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
				add_assignee = { lhs = "<leader>aa", desc = "add assignee" },
				remove_assignee = { lhs = "<leader>ad", desc = "remove assignee" },
				create_label = { lhs = "<leader>lc", desc = "create label" },
				add_label = { lhs = "<leader>la", desc = "add label" },
				remove_label = { lhs = "<leader>ld", desc = "remove label" },
				goto_issue = { lhs = "<leader>gi", desc = "go to issue" },
				add_comment = { lhs = "<leader>ca", desc = "add comment" },
				delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
				next_comment = { lhs = "]c", desc = "go to next comment" },
				prev_comment = { lhs = "[c", desc = "go to previous comment" },
				react_hooray = { lhs = "<leader>rp", desc = "add/remove 🎉 reaction" },
				react_heart = { lhs = "<leader>rh", desc = "add/remove ❤️ reaction" },
				react_eyes = { lhs = "<leader>re", desc = "add/remove 👀 reaction" },
				react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove 👍 reaction" },
				react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove 👎 reaction" },
				react_rocket = { lhs = "<leader>rr", desc = "add/remove 🚀 reaction" },
				react_laugh = { lhs = "<leader>rl", desc = "add/remove 😄 reaction" },
				review_start = { lhs = "<leader>vs", desc = "start review" },
				review_resume = { lhs = "<leader>vr", desc = "resume review" },
			},
			pull_request = {
				checkout_pr = { lhs = "<leader>po", desc = "checkout PR" },
				merge_pr = { lhs = "<leader>pm", desc = "merge commit PR" },
				squash_and_merge_pr = { lhs = "<leader>psm", desc = "squash and merge PR" },
				list_commits = { lhs = "<leader>pc", desc = "list commits" },
				list_changed_files = { lhs = "<leader>pf", desc = "list changed files" },
				show_pr_diff = { lhs = "<leader>pd", desc = "show PR diff" },
				approve_pr = { lhs = "<leader>pa", desc = "approve PR" },
				reject_pr = { lhs = "<leader>pr", desc = "reject PR" },
				review_pr = { lhs = "<leader>pv", desc = "review PR" },
				close_pr = { lhs = "<leader>pc", desc = "close PR" },
				reopen_pr = { lhs = "<leader>po", desc = "reopen PR" },
				reload = { lhs = "<C-r>", desc = "reload PR" },
				open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
				copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
				goto_file = { lhs = "gf", desc = "go to file" },
				add_assignee = { lhs = "<leader>aa", desc = "add assignee" },
				remove_assignee = { lhs = "<leader>ad", desc = "remove assignee" },
				create_label = { lhs = "<leader>lc", desc = "create label" },
				add_label = { lhs = "<leader>la", desc = "add label" },
				remove_label = { lhs = "<leader>ld", desc = "remove label" },
				goto_issue = { lhs = "<leader>gi", desc = "go to issue" },
				add_comment = { lhs = "<leader>ca", desc = "add comment" },
				delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
				next_comment = { lhs = "]c", desc = "go to next comment" },
				prev_comment = { lhs = "[c", desc = "go to previous comment" },
				react_hooray = { lhs = "<leader>rp", desc = "add/remove 🎉 reaction" },
				react_heart = { lhs = "<leader>rh", desc = "add/remove ❤️ reaction" },
				react_eyes = { lhs = "<leader>re", desc = "add/remove 👀 reaction" },
				react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove 👍 reaction" },
				react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove 👎 reaction" },
				react_rocket = { lhs = "<leader>rr", desc = "add/remove 🚀 reaction" },
				react_laugh = { lhs = "<leader>rl", desc = "add/remove 😄 reaction" },
				review_start = { lhs = "<leader>vs", desc = "start review" },
				review_resume = { lhs = "<leader>vr", desc = "resume review" },
			},
			review_thread = {
				goto_issue = { lhs = "<leader>gi", desc = "go to issue" },
				add_comment = { lhs = "<leader>ca", desc = "add comment" },
				add_suggestion = { lhs = "<leader>sa", desc = "add suggestion" },
				next_comment = { lhs = "]c", desc = "go to next comment" },
				prev_comment = { lhs = "[c", desc = "go to previous comment" },
				next_thread = { lhs = "]t", desc = "go to next thread" },
				prev_thread = { lhs = "[t", desc = "go to previous thread" },
				close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
			},
			submit_win = {
				approve_review = { lhs = "<C-a>", desc = "approve review" },
				comment_review = { lhs = "<C-m>", desc = "comment review" },
				request_changes = { lhs = "<C-r>", desc = "request changes review" },
				close_review_win = { lhs = "<C-c>", desc = "close review window" },
			},
			diff_view = {
				add_review_comment = { lhs = "<leader>ca", desc = "add review comment" },
				add_review_suggestion = { lhs = "<leader>sa", desc = "add review suggestion" },
				focus_files = { lhs = "<leader>e", desc = "focus files panel" },
				toggle_files = { lhs = "<leader>b", desc = "toggle files panel" },
				next_thread = { lhs = "]t", desc = "next thread" },
				prev_thread = { lhs = "[t", desc = "previous thread" },
				close_diff_win = { lhs = "<C-c>", desc = "close diff window" },
				close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
			},
			file_panel = {
				next_entry = { lhs = "j", desc = "move to next changed file" },
				prev_entry = { lhs = "k", desc = "move to prev changed file" },
				select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
				refresh_files = { lhs = "R", desc = "refresh changed files panel" },
				focus_files = { lhs = "<leader>e", desc = "focus files panel" },
				toggle_files = { lhs = "<leader>b", desc = "toggle files panel" },
				select_next_entry = { lhs = "]f", desc = "view next changed file" },
				select_prev_entry = { lhs = "[f", desc = "view previous changed file" },
				close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
				toggle_viewed = { lhs = "<leader>v", desc = "toggle viewer viewed state" },
			},
		},
	},
}
